### ISSUE TITLE
TextRecognizer works ok on Android but the result letters are all corrupted on iOS

### ISSUE THREAD

**Issue by kodol73** [bharat-biradar/Google-Ml-Kit-plugin#231] opened 2022-04-22 16:03 UTC
Hi,

I got recommended to use google_mlkit_text_recognition instead of google_ml_kit as followes
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/207

However, it still works ok on Android but not on iOS using google_mlkit_text_recognition as using google_ml_kit

recognizedText.text look ok on Android but the letters in it are all corrupted on iOS
For now, I need only English TextRecognizer

    import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart';

    textRecognizer = TextRecognizer(script: TextRecognitionScript.latin);
    final File? imageFile = await getImage(ImageSource.gallery);

    if(imageFile != null) {
      final inputImage = InputImage.fromFile(imageFile);
      final RecognizedText recognizedText = await textRecognizer.processImage(inputImage);
  
      String text = recognizedText.text;
      print('${this.className} extractText : ' + text);
   }

google_mlkit_text_recognition 0.0.1

My development environment is as followes
iOS 14.7.1
Xcode 13.3

Please help me to solve this issue
Thanks in advance

**Comment by fbernaly** [comment] 2022-04-22 16:09
@kodol73 : could you share an image of the text you are trying to recognize? I have been trying text recognizer and it works for me.

**Comment by fbernaly** [comment] 2022-04-22 16:16
Here you have some screenshoot of the example app in iOS and it is working.

![IMG_0050](https://user-images.githubusercontent.com/7014968/164754138-c19a3b63-900c-4521-a3ab-86ab91e9fa18.PNG)

![IMG_0051](https://user-images.githubusercontent.com/7014968/164754152-2a3dc7d0-c597-4d9d-ac4d-7a61b16278c7.PNG)

**Comment by pdhiepCMCJapan** [comment] 2022-04-26 06:36
i have a same problem, it detect wrong text when run on IOS flutter

**Comment by kodol73** [comment] 2022-04-26 09:31
> 

It seems that some images of text are recognized correctly, but some other images of text are corrupted
I just tried with example app, but has the same result

The result of recognizing below image is corrupted
Please check with the below image


![IMG_1391](https://user-images.githubusercontent.com/11918801/165269422-5b9b03ac-e02f-4711-a16d-9a30a97797d4.JPG)

**Comment by fbernaly** [comment] 2022-04-26 21:02
@kodol73 : I tried your image with the example app and so far it does not look corrupted to me. It looks pretty much good to me.

![IMG_0052](https://user-images.githubusercontent.com/7014968/165391594-2640b595-dc5a-482a-b9f2-dcaa7e54add5.PNG)

**Comment by kodol73** [comment] 2022-04-27 00:35
> 
You tried it on iPhone, right?
Can you please let me know your phone model and iOS version?

**Comment by fbernaly** [comment] 2022-04-27 01:14
I tried with both an iPhone 11 and iPhone 6S, both with iOS 15 and I am using Xcode 13.3

**Comment by kodol73** [comment] 2022-04-28 16:06
> I tried with both an iPhone 11 and iPhone 6S, both with iOS 15 and I am using Xcode 13.3

it's weird, I just upgraded iOS to 15.4.1, but the same result
It generated corrupted text like the following with the image
```
T
T
ooo
5
```

Just in case, I test with google_ml_kit 0.8.0 because example app uses google_ml_kit

Please help me to solve this issue

**Comment by codyfilatov** [comment] 2022-04-28 21:11
I had this same issue, but resolved it on iOS. 

Still testing android but I am passing the File from camera plugin cameraController.takePicture() as the InputImage.fromFile(imageFile) and looking at text it had almost no relevant data, and any data it did have was like:
A
ooD
TM

After removing the google_ml_kit plugin, and replacing it with only the google_mlkit_text_recognition: ^0.2.0 it works fine. No idea why to be honest, but specifying just text recognition instead of the umbrella plugin resolved. Would like to hear some details on this if there are any.

**Comment by fbernaly** [comment] 2022-04-28 21:25
Thanks @codyfilatov for the suggestion.

Do you still have issues with Android? both platforms are working okay?

@kodol73 : give it a try

**Comment by codyfilatov** [comment] 2022-04-28 22:13
Both platforms are working okay now. 
Although I did not have this issue with Android to begin with.

The only issue I am having now on iOS is the orientation of my image when processing, it thinks it is in landscape when it is in portrait, so the bounding boxes are messed up, does not happen on Android. My image does not have any exif orientation data. I would be nice to have if no orientation data exists to predict based on the height/width, looks like it defaults to Landscape if no data exists. But that's another issue I can figure out.

Hope OP resolves issue with the dependency change.
Thanks

**Comment by fbernaly** [comment] 2022-04-28 22:20
@codyfilatov: once you figure the orientation out, share here or create another issue if necessary. I have seen issues with different orientations as well.

**Comment by kodol73** [comment] 2022-04-29 11:27
I just tested the newly released version of google_mlkit_text_recognition, 0.2.0, nothing else changed 
The issue doesn't appear any more

Thanks

**Comment by codyfilatov** [comment] 2022-04-29 11:35
> @codyfilatov: once you figure the orientation out, share here or create another issue if necessary. I have seen issues with different orientations as well.

Sharing here just as a note.
The orientation issue was caused by no EXIF orientation data on the image in iOS taken from the camera plugin takePicture function. Since the image file had no EXIF orientation data I assume the text regognizer (and barcode scanner) was returning odd (not incorrect) values. 

The values did not translate as expected as when I set a Container DecorationImage as the same file the image is displayed correctly as taken, but the values were printed mirrored and counter clockwise consistently. 

After using the image package to set the EXIF orientation data to 1 and rewriting the bytes to a new file, then passing that file to MLkit the boundingBox values were as expected.

**Comment by codyfilatov** [comment] 2022-04-29 14:28
```
XFile imageCaptureXFile = await this.cameraController!.takePicture();
File imageFile = File(imageCaptureXFile.path);
this.imageFile = imageFile;
img.Image? image = img.decodeImage(await imageFile.readAsBytes());
if(image == null){
    Util.showToast('Image was not found.');
    this.isConfirming = false;
    this.imageFile = null;
    setState(() {});
    return;
}
if(!image.exif.hasOrientation){
    print('Baking orientation into image...');
    image.exif.orientation = 1;
    File orientatedImageFile = File((await getTemporaryDirectory()).path + Uuid().v4() + '.jpg');
    await orientatedImageFile.create();
    await orientatedImageFile.writeAsBytes(img.encodeJpg(image));
    await imageFile.delete();
    imageFile = orientatedImageFile;
    this.imageFile = orientatedImageFile;

    image = img.decodeImage(await orientatedImageFile.readAsBytes());
    if(image == null){
        setState(() {});
        return;
    }
}
```

This is what I use for my use case. Keep in mind I only want portrait.
I use the package:image/image.dart . Ignore the bad code, I'll clean it up later.

```
TextRecognizer textDetector = TextRecognizer(script: TextRecognitionScript.latin);
RecognizedText recognisedText = await textDetector.processImage(InputImage.fromFile(imageFile));
```

**Comment by fbernaly** [comment] 2022-04-29 20:19
Closing this issue.

Fix: [google_mlkit_text_recognition](https://pub.dev/packages/google_mlkit_text_recognition) instead of `google_ml_kit`.

More details here: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_text_recognition

Moving `InputImage` and `InputImageRotation` issues to: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/240

**Closed by fbernaly** 2022-04-29 20:19 UTC
