### ISSUE TITLE
MLKNilLocalModel on iOS

### ISSUE THREAD

**Issue by azharj96** [bharat-biradar/Google-Ml-Kit-plugin#55] opened 2021-06-07 15:07 UTC
### Objective: 
Image labelling using custom model done in real-time. Should run on Android & iOS.

### Steps done so far: 
Used code here: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/example/lib/VisionDetectorViews/label_detector_view.dart

With the stated adaptations for using a custom model (e.g. uncommenting `processImageWithCustomModel`). 

As I am building for iOS, the path of the model is `assets/ml/model.tflite` and not in the android assets as mentions in a comment on the above link.

I experimented with both `CustomTrainedModel.asset` and `CustomTrainedModel.file` with no luck.

Please let me know how to solve the below.

### Result
When building on iOS, I get the following:
```
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
*** Terminating app due to uncaught exception 'MLKNilLocalModel', reason: 'Local model must not be nil.'
*** First throw call stack:
(0x18135a754 0x195e217a8 0x18124f7e0 0x103655154 0x106199d94 0x10619945c 0x106199190 0x106198f6c 0x108d92d60 0x108aa407c 0x108dad370 0x108d474d4 0x108d49cfc 0x1812d522c 0x1812d4e28 0x1812d4278 0x1812ce02c 0x1812cd360 0x19890b734 0x183d48584 0x183d4ddf4 0x10257275c 0x180f89cf8)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001af471334 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1af471334 <+8>:  b.lo   0x1af471354               ; <+40>
    0x1af471338 <+12>: pacibsp 
    0x1af47133c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1af471340 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
```

**Comment by bharat-biradar** [comment] 2021-06-08 04:17
@azharj96 Did you take the first step mentioned [here](https://developers.google.com/ml-kit/vision/image-labeling/custom-models/ios#configure_a_local_model_source)  while copying the model.

**Comment by bharat-biradar** [comment] 2021-06-08 13:42
@azharj96 On taking a second look, I noticed that the problem was on the native side of the code. We'll fix it shortly and get back to you.

**Comment by fbernaly** [comment] 2021-06-09 15:27
@azharj96 : we just merged this PR https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/57 . I think this fixes this issue. Could you double check and if yes then let's close this issue.

**Comment by azharj96** [comment] 2021-06-10 10:56
@fbernaly when attempting to build for ios, I get the following error: `Receiver 'MLKLocalModel' for class message is a forward declaration`

Full output:

```
Xcode build done.                                            5.1s
Failed to build iOS app
Error output from Xcode build:
↳
    2021-06-10 11:54:49.636 xcodebuild[4517:35503]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 00008030-0014142826E2802E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fe406af1b90>
    Method:   -platform
    Thread:   <NSThread: 0x7fe40171c990>{number = 3, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-06-10 11:54:49.876 xcodebuild[4517:35508]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 00008030-0014142826E2802E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fe406af1b90>
    Method:   -platform
    Thread:   <NSThread: 0x7fe40212b5b0>{number = 7, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:83:35: error: receiver 'MLKLocalModel' for class message is a forward declaration
        MLKLocalModel *localModel = [[MLKLocalModel alloc] initWithPath: path];
                                      ^~~~~~~~~~~~~
    In module 'MLKitImageLabelingCustom' imported from /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:4:
    /Users/azharjamal/FlutterProjects/vizor/ios/Pods/MLKitImageLabelingCustom/Frameworks/MLKitImageLabelingCustom.framework/Headers/MLKCustomImageLabelerOptions.h:7:8: note: forward declaration of class here
    @class MLKLocalModel;
           ^
    /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:83:34: error: receiver type 'MLKLocalModel' for instance message is a forward declaration
        MLKLocalModel *localModel = [[MLKLocalModel alloc] initWithPath: path];
                                     ^~~~~~~~~~~~~~~~~~~~~
    In module 'MLKitImageLabelingCustom' imported from /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:4:
    /Users/azharjamal/FlutterProjects/vizor/ios/Pods/MLKitImageLabelingCustom/Frameworks/MLKitImageLabelingCustom.framework/Headers/MLKCustomImageLabelerOptions.h:7:8: note: forward declaration of class here
    @class MLKLocalModel;
           ^
    /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:79:15: warning: unused variable 'modelType' [-Wunused-variable]
        NSString *modelType = optionsData[@"customModel"];
                  ^
    1 warning and 2 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Encountered error while building for device.

```

**Comment by marcus-bornman** [comment] 2021-06-14 17:59
> @fbernaly when attempting to build for ios, I get the following error: `Receiver 'MLKLocalModel' for class message is a forward declaration`
> 
> Full output:
> 
> ```
> Xcode build done.                                            5.1s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     2021-06-10 11:54:49.636 xcodebuild[4517:35503]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
>     Details:  (null) deviceType from 00008030-0014142826E2802E was NULL when -platform called.
>     Object:   <DTDKMobileDeviceToken: 0x7fe406af1b90>
>     Method:   -platform
>     Thread:   <NSThread: 0x7fe40171c990>{number = 3, name = (null)}
>     Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
>     2021-06-10 11:54:49.876 xcodebuild[4517:35508]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
>     Details:  (null) deviceType from 00008030-0014142826E2802E was NULL when -platform called.
>     Object:   <DTDKMobileDeviceToken: 0x7fe406af1b90>
>     Method:   -platform
>     Thread:   <NSThread: 0x7fe40212b5b0>{number = 7, name = (null)}
>     Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:83:35: error: receiver 'MLKLocalModel' for class message is a forward declaration
>         MLKLocalModel *localModel = [[MLKLocalModel alloc] initWithPath: path];
>                                       ^~~~~~~~~~~~~
>     In module 'MLKitImageLabelingCustom' imported from /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:4:
>     /Users/azharjamal/FlutterProjects/vizor/ios/Pods/MLKitImageLabelingCustom/Frameworks/MLKitImageLabelingCustom.framework/Headers/MLKCustomImageLabelerOptions.h:7:8: note: forward declaration of class here
>     @class MLKLocalModel;
>            ^
>     /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:83:34: error: receiver type 'MLKLocalModel' for instance message is a forward declaration
>         MLKLocalModel *localModel = [[MLKLocalModel alloc] initWithPath: path];
>                                      ^~~~~~~~~~~~~~~~~~~~~
>     In module 'MLKitImageLabelingCustom' imported from /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:4:
>     /Users/azharjamal/FlutterProjects/vizor/ios/Pods/MLKitImageLabelingCustom/Frameworks/MLKitImageLabelingCustom.framework/Headers/MLKCustomImageLabelerOptions.h:7:8: note: forward declaration of class here
>     @class MLKLocalModel;
>            ^
>     /Users/azharjamal/.pub-cache/git/Google-Ml-Kit-plugin-8050b0e251e647c241a85f9be9c60e56c3810cbd/ios/Classes/vision/ImageLabeler.m:79:15: warning: unused variable 'modelType' [-Wunused-variable]
>         NSString *modelType = optionsData[@"customModel"];
>                   ^
>     1 warning and 2 errors generated.
>     note: Using new build system
>     note: Building targets in parallel
>     note: Planning build
>     note: Constructing build description
> 
> Encountered error while building for device.
> ```

I can confirm I am getting the same issue.

**Comment by fbernaly** [comment] 2021-06-14 19:26
it was missing an `#import` . Here is the PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/63

**Closed** 2021-06-15 16:24 UTC
