### ISSUE TITLE
Conflicting with new firebase packages  "CocoaPods could not find compatible versions for pod "GoogleDataTransport"

### ISSUE THREAD

**Issue by usestrive** [bharat-biradar/Google-Ml-Kit-plugin#20] opened 2021-05-19 07:49 UTC

**Comment by bharat-biradar** [comment] 2021-05-19 14:18
@usestrive Can you please be more specific about the issue. Actually, this plugin doesn't support IOS yet may be the problem is being caused by that.

**Comment by fbernaly** [comment] 2021-05-19 20:06
@usestrive:  I added iOS support for Face Detection in this PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/21. Once it is approved and merged, clone the the repo and give it a try. You only need to set your development team in the Xcode project to run the example app.

**Closed** 2021-05-26 01:47 UTC
